-- LORGUS RP messages
create table if not exists public.rp_messages (
    id bigint generated by default as identity primary key,
    character_id uuid not null references public.characters(id) on delete cascade,
    player_id uuid not null references auth.users(id) on delete cascade,
    presence_type text not null check (presence_type in ('location', 'road')),
    region text,
    location text,
    from_region text,
    from_location text,
    to_region text,
    to_location text,
    body text not null check (char_length(trim(body)) between 1 and 10000),
    created_at timestamptz not null default now()
);

create index if not exists rp_messages_location_idx
on public.rp_messages (region, location, created_at);

create index if not exists rp_messages_road_idx
on public.rp_messages (from_region, from_location, to_region, to_location, created_at);

alter table public.rp_messages enable row level security;

drop policy if exists "rp_messages_select_authenticated" on public.rp_messages;
create policy "rp_messages_select_authenticated"
on public.rp_messages for select
to authenticated
using (true);

drop policy if exists "rp_messages_insert_own" on public.rp_messages;
create policy "rp_messages_insert_own"
on public.rp_messages for insert
to authenticated
with check (player_id = auth.uid());

alter table public.rp_messages replica identity full;
