-- LORGUS RP schema
-- Canonical migration for RP presence and messages.

create table if not exists public.rp_presence (
    character_id uuid primary key references public.characters(id) on delete cascade,
    player_id uuid not null references auth.users(id) on delete cascade,
    presence_type text not null check (presence_type in ('location', 'road')),
    region text,
    location text,
    from_region text,
    from_location text,
    to_region text,
    to_location text,
    visibility text not null default 'public' check (visibility in ('public', 'hidden')),
    entered_at timestamptz,
    started_at timestamptz,
    updated_at timestamptz not null default now()
);

create index if not exists rp_presence_location_idx on public.rp_presence (region, location);
create index if not exists rp_presence_destination_idx on public.rp_presence (to_region, to_location);
alter table public.rp_presence enable row level security;

drop policy if exists "rp_presence_select_public" on public.rp_presence;
create policy "rp_presence_select_public" on public.rp_presence
for select to authenticated
using (visibility = 'public' or player_id = auth.uid());

drop policy if exists "rp_presence_insert_own" on public.rp_presence;
create policy "rp_presence_insert_own" on public.rp_presence
for insert to authenticated
with check (player_id = auth.uid());

drop policy if exists "rp_presence_update_own" on public.rp_presence;
create policy "rp_presence_update_own" on public.rp_presence
for update to authenticated
using (player_id = auth.uid())
with check (player_id = auth.uid());

drop policy if exists "rp_presence_delete_own" on public.rp_presence;
create policy "rp_presence_delete_own" on public.rp_presence
for delete to authenticated
using (player_id = auth.uid());

alter table public.rp_presence replica identity full;

create or replace function public.set_rp_presence(
    p_character_id uuid, p_presence_type text, p_region text default null,
    p_location text default null, p_from_region text default null,
    p_from_location text default null, p_to_region text default null,
    p_to_location text default null, p_visibility text default 'public'
)
returns public.rp_presence language plpgsql security invoker as $$
declare v_presence public.rp_presence;
begin
    insert into public.rp_presence (
        character_id, player_id, presence_type, region, location,
        from_region, from_location, to_region, to_location, visibility,
        entered_at, started_at, updated_at
    ) values (
        p_character_id, auth.uid(), p_presence_type, p_region, p_location,
        p_from_region, p_from_location, p_to_region, p_to_location, p_visibility,
        case when p_presence_type = 'location' then now() else null end,
        case when p_presence_type = 'road' then now() else null end, now()
    )
    on conflict (character_id) do update set
        player_id = excluded.player_id, presence_type = excluded.presence_type,
        region = excluded.region, location = excluded.location,
        from_region = excluded.from_region, from_location = excluded.from_location,
        to_region = excluded.to_region, to_location = excluded.to_location,
        visibility = excluded.visibility, entered_at = excluded.entered_at,
        started_at = excluded.started_at, updated_at = now()
    returning * into v_presence;
    return v_presence;
end;
$$;

create or replace function public.clear_rp_presence(p_character_id uuid)
returns void language sql security invoker as $$
    delete from public.rp_presence
    where character_id = p_character_id and player_id = auth.uid();
$$;

create table if not exists public.rp_messages (
    id bigint generated by default as identity primary key,
    character_id uuid not null references public.characters(id) on delete cascade,
    player_id uuid not null references auth.users(id) on delete cascade,
    presence_type text not null check (presence_type in ('location', 'road')),
    region text, location text, from_region text, from_location text,
    to_region text, to_location text,
    body text not null check (char_length(trim(body)) between 1 and 10000),
    created_at timestamptz not null default now()
);

create index if not exists rp_messages_location_idx
on public.rp_messages (region, location, created_at);
create index if not exists rp_messages_road_idx
on public.rp_messages (from_region, from_location, to_region, to_location, created_at);

alter table public.rp_messages enable row level security;

drop policy if exists "rp_messages_select_authenticated" on public.rp_messages;
create policy "rp_messages_select_authenticated" on public.rp_messages
for select to authenticated using (true);

drop policy if exists "rp_messages_insert_own" on public.rp_messages;
create policy "rp_messages_insert_own" on public.rp_messages
for insert to authenticated with check (player_id = auth.uid());

alter table public.rp_messages replica identity full;
